import GlobalStateProvider from "@/providers/GlobalStateProvider";
import "./globals.css";
import { Toaster } from "sonner";

export const metadata = {
  title: "WellnessZ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Toaster richColors />
        <GlobalStateProvider>
          {children}
        </GlobalStateProvider>
      </body>
    </html>
  );
}
