import GlobalStateProvider from "@/providers/GlobalStateProvider";
import "./globals.css";
import { Toaster } from "sonner";
import { SWRConfig } from "swr";

export const metadata = {
  title: "WellnessZ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Toaster richColors />
        <GlobalStateProvider>
          <SWRConfig value={{ revalidateOnFocus: false, revalidateIfStale: false }}>
            {children}
          </SWRConfig>
        </GlobalStateProvider>
      </body>
    </html>
  );
}
